# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7
  aws-eks: circleci/aws-eks@1.1.0
  kubernetes: circleci/kubernetes@0.4.0
  aws-cli: circleci/aws-cli@1.4.0
jobs:
  cfn-lint:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Install cfn lint 
          command: |
            pip install cfn-lint
      - run:
          name: Validate CloudFormation template
          command: |
            cfn-lint infrastructure/capstone-infra.yml
workflows:
  default: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - cfn-lint
