apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-frontend-$COLOR
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capstone-frontend
      role: $COLOR
  template:
    metadata:
      labels:
        app: capstone-frontend
        role: $COLOR
    spec:
      containers:
        - image: duyhuynhdn/capstone-frontend:latest
          name: capstone-frontend
          imagePullPolicy: Always
          ports:
          - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
      restartPolicy: Always