apiVersion: v1
kind: Service
metadata:
  name: capstone-frontend
  labels:
    app: capstone-frontend
    role: $COLOR
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80    
  selector:
    app: capstone-frontend
    role: $COLOR